### ISSUE TITLE
JPQL null param error

### ISSUE THREAD

**Issue by flascaray** [olavloite/spanner-hibernate#1]
When i pass a null value param to a JPQL query i get the next error:

` nl.topicus.jdbc.shaded.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: No matching signature for operator = for argument types: STRING, BOOL. Supported signature: ANY = ANY [at 1:401]
...and contact0_.provider_id=@p1 and (@p2 is null or contact0_.position_id=@p...`

In the query i use the next WHERE clause

`WHERE :positionId IS NULL OR c.position.id = :positionId`

**Comment by olavloite** [comment]
Confirmed as a bug, but in the jdbc driver and not in the Hibernate dialect. The progress of this issue can be followed in olavloite/spanner-jdbc#54
