### ISSUE TITLE
Question: It is possible to specify a secondary index?

### ISSUE THREAD

**Issue by flascaray** [olavloite/spanner-hibernate#4]
According to the Spanner documentation:

> Cloud Spanner chooses an index automatically only in rare circumstances. In particular, Cloud Spanner does not automatically choose a secondary index if the query requests any columns that are not stored in the index.

It is possible to specify a secondary index in JPQL or through an annotation?

**Comment by olavloite** [comment]
No, that is only possible by using a native query. JPQL will not accept any index hints.
